URI Builder for ad types
lm-sushant-deshpande/lemma-infibid-sample-app pull request #1
Opened 2024-08-12 08:55 UTC by lm-Lakhan-Balmiki

URL Builder according to the Ad types.

2024-08-12 10:02 UTC, lm-sushant-deshpande requested changes

2024-08-12 10:02 UTC, lm-sushant-deshpande commented on InfiBidSampleApp/app/src/main/java/com/example/InfiBidSampleApp/MainActivity.java
> +            "?test=1&tmax=3000&vw=1080&vh=1920&apid=abcd&apdom=%22test.prebid.com%22&apbndl=%22com.prebid.test%22&ip=%22192.168.1.2%22&vmimes=[%22video%2Fmp4%22%2C%20%22video%2Fog3%22]&wpid=178&waid=
No need of this variable

2024-08-16 07:08 UTC, lm-Lakhan-Balmiki commented on InfiBidSampleApp/app/src/main/java/com/example/InfiBidSampleApp/MainActivity.java
> +            "?test=1&tmax=3000&vw=1080&vh=1920&apid=abcd&apdom=%22test.prebid.com%22&apbndl=%22com.prebid.test%22&ip=%22192.168.1.2%22&vmimes=[%22video%2Fmp4%22%2C%20%22video%2Fog3%22]&wpid=178&waid=
Resolved the issue.

2024-08-19 06:54 UTC, lm-sushant-deshpande requested changes
1. Use .idea/** in gitignore
2. Use https urls and remove network config file

2024-08-21 05:43 UTC, lm-sushant-deshpande requested changes
1. Replace `sandbox.lemmatechnologies.com` with `lemmadigital.com`

2024-08-21 05:43 UTC, lm-sushant-deshpande commented on InfiBidSampleApp/app/src/main/java/com/example/InfiBidSampleApp/GAMHBAdTagUrlBuilder.java
> +        new Thread(() -> {
Remove thread

2024-08-21 05:43 UTC, lm-sushant-deshpande commented on InfiBidSampleApp/app/src/main/java/com/example/InfiBidSampleApp/GAMHBAdTagUrlBuilder.java
> +                        }
remove multiple try catch bolck

2024-08-21 05:43 UTC, lm-sushant-deshpande commented on InfiBidSampleApp/app/src/main/java/com/example/InfiBidSampleApp/MainActivity.java
> +                        Log.e(TAG, "Failed to fetch targeting data", e);
call `startIMAPlayerActivity(url);`

2024-08-21 05:43 UTC, lm-sushant-deshpande commented on InfiBidSampleApp/app/src/main/java/com/example/InfiBidSampleApp/MainActivity.java
> +                startIMAPlayerActivity(url);
Remove this

2024-08-21 05:43 UTC, lm-sushant-deshpande commented on InfiBidSampleApp/app/src/main/java/com/example/InfiBidSampleApp/MainActivity.java
> +                String vastUrl = "http://sandbox.lemmatechnologies.com/infibid/v1/video/vast";
Move this url inside `LemmaVastAdTagUrlBuilder `

2024-08-21 10:02 UTC, lm-sushant-deshpande requested changes

2024-08-21 10:02 UTC, lm-sushant-deshpande commented on InfiBidSampleApp/app/src/main/java/com/example/InfiBidSampleApp/GAMHBAdTagUrlBuilder.java
> +        void onFailure(Exception e);
Use Error

2024-08-21 10:02 UTC, lm-sushant-deshpande commented on InfiBidSampleApp/app/src/main/java/com/example/InfiBidSampleApp/MainActivity.java
> +                urlBuilder.requestHBAdTargeting(new GAMHBAdTagUrlBuilder.TargetingCallback() {
```suggestion
                urlBuilder.build(new GAMHBAdTagUrlBuilder.TargetingCallback() {
```

2024-08-21 10:02 UTC, lm-sushant-deshpande commented on InfiBidSampleApp/app/src/main/java/com/example/InfiBidSampleApp/MainActivity.java
> +                String url = urlBuilder.getUrl();
```suggestion
                String url = urlBuilder.build();
```

2024-08-21 13:16 UTC, lm-sushant-deshpande approved these changes

2024-08-21 13:16 UTC, merged